# Site settings
name: Matin Keshmiri
title: Matin Keshmiri | AR/VR Developer 
description: Unity 3D Developer focused on Augmented/Virtual/Mixed Reality
url: https://MatinKeshmiri.github.io/
baseurl: ''
email: mkeshmiri1989@gmail.com
cover: https://bchiang7.github.io/img/og.png
logo: https://bchiang7.github.io/img/emojis/technologist.png
resume: https://bchiang7.github.io/resume.pdf
social:
  - title: email
    url: mailto:mkeshmiri1989@gmail.com
  
  - title: github
    url: https://github.com/MatinKeshmiri
  - title: linkedin
    url: https://www.linkedin.com/in/matin-keshmiri-318552153

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
